### ISSUE TITLE
Issue with dependent variable local_aerodynamic_g_load

### ISSUE THREAD

**Issue by jacopocarra** [tudat-team/tudatpy#101]
When trying to save the dependent variable "local_aerodynamic_g_load" I get the following error:
"RuntimeError: Error when getting acceleration between bodies, no translational dynamics models by  acting on Capsule are found"
I've already spoken with Dominic and it looks like it is an issue with the python exposure of this function. Thank you!

**Comment by DominicDirkx** [comment]
We've made the updates to the code and docs, but it will take a while for these to show up (just pushed to the develop branch). Thanks for pointing this issue out!
