### ISSUE TITLE
"Silly" default behaviour of spherical harmonics parameter sets

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudatpy#102]
Spherical harmonics parameter sets created by 

- `estimation_setup.parameter.spherical_harmonics_c_coefficients` and 
- `estimation_setup.parameter.spherical_harmonics_s_coefficients`

include an entry for the degree, order (0,0) coefficient, which one should not estimate nor consider in sensitivity analyses. 
Maybe this term should be excluded by default? On top (or instead), it would be helpful for the naive user to adopt a little note into the docstrings (for the API reference), that for estimation / sensitivity of GM in combination with SH coefficients, one should go through the dedicated `gravitational_parameter` parameter type, and add it to the parameter set alongside the spherical harmonics coefficients.

**Comment by DominicDirkx** [comment]
Fixed in this commit: 

https://github.com/tudat-team/tudat/commit/10ee98ae93285464f58ebda82e265925e407a0db

I also added some more checks (no negative degrees, no order 0 sine coefficients).

Thanks for pointing this out!
