### ISSUE TITLE
Retrieving a list of links from an ObservationCollection object.

### ISSUE THREAD

**Issue by tristandijkstra** [tudat-team/tudatpy#113]
Hi,

Related to these two PRs i'd like to retrieve a list of linkDefinitions from an observation collection. Below is an example of how I  currently do it.

https://github.com/tudat-team/tudatpy-examples/pull/28
https://github.com/tudat-team/tudatpy/pull/110

```
# Transform the MPC observations into a tudat compatible format.
observation_collection, links = batch.to_tudat(bodies=bodies)

# set create angular_position settings for each link in the list.
observation_settings_list = list()
for link in list(links.values()):
    observation_settings_list.append(observation.angular_position(link))
```

**Comment by DominicDirkx** [comment]
Functionality has been added with latest commit to develop:

https://github.com/tudat-team/tudatpy/commit/c967acb83f43dc8b19c5bb44bdf338659d4e94a5

and associated commit to tudat develop branch.

The new ObservationCollection.get_link_definitions_for_observables function (with observable type as input) returns a list of LinkDefinition objects used for that observable
