### ISSUE TITLE
Example jupyter notebook (Brightspace) → error: acceleration + cannonball_radiation_pressure

### ISSUE THREAD

**Issue by transferorbit** [tudat-team/tudatpy#13]
After a fresh (and wrinkle-free) install of `TudatPy` following Brightspace and readthedocs steps, I ran the _example jupyter notebook_ from the _Survey/Announcement_ on the [NumAstro Brightspace page](https://brightspace.tudelft.nl/d2l/lms/survey/user/attempt/survey_start_frame.d2l?isprv=1&si=49546&ou=278334). 
Upon execution, this immediately throws the error below, but if I’m not mistaken, the fix is easy:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-0f8b7fcdb525> in <module>
     78     Sun=
     79     [
---> 80         propagation_setup.acceleration.cannonball_radiation_pressure_(),
     81         propagation_setup.acceleration.point_mass_gravity()
     82     ],

AttributeError: module 'tudatpy.kernel.simulation.propagation_setup.acceleration' has no attribute ‘cannonball_radiation_pressure_'
```

Changing
`propagation_setup.acceleration.cannonball_radiation_pressure_()`
to 
`propagation_setup.acceleration.cannonball_radiation_pressure()`
by removing the final underscore before the parentheses results in all the plots being produced as expected.

**At the risk of borking things, I have already taken the liberty of removing the underscore** and altering the source file on Brightspace. I believe, therefore that this issue can immediately be closed, but a second-opinion confirmation would be nice.

**Comment by ggarrett13** [comment]
Problem with the code on brightspace, thanks for the reporting @transferorbit!
