### ISSUE TITLE
Documentation 404?

### ISSUE THREAD

**Issue by s-m-e** [tudat-team/tudatpy#16]
https://tudat-team.github.io/tudatpy/ as well as https://tudat-team.github.io as linked in the readme file for documentation throws HTTP 404.

**Comment by transferorbit** [comment]
The link to the documentation has been updated (to: [https://tudat-space.readthedocs.io](https://tudat-space.readthedocs.io)). No separate link to  [https://tudat-team.github.io](https://tudat-team.github.io) exists in the `README.md` file (although that link does also throw a `404`.
