### ISSUE TITLE
Remove unnecessary Python files from repo

### ISSUE THREAD

**Issue by yiquintero** [tudat-team/tudatpy#169]
## Description

A list of all the Python files in the the tudatpy repo was created with the purpose of determining which files should be:
- included in the API docs
- kept, but not included in the API docs
- removed from the repo

## Solution

It was determined the following files in the tudatpy repo should be removed from the repo:
- bodies/*
- cli/*
- apps/*
- elements.py
- prototype.py

**Comment by DominicDirkx** [comment]
@yiquintero Have these removals been made part of one of the PRs that you opened, or are they still to be done?

**Comment by yiquintero** [comment]
These files have been removed as part of the tudatpy project reestructuring. The only files that remain are the ones inside the `cli` directory, which are now located in [tudatpy/temp/cli](https://github.com/tudat-team/tudatpy/tree/develop/tudatpy/temp/cli).
