### ISSUE TITLE
Should the documentation be updated?

### ISSUE THREAD

**Issue by spacefan** [tudat-team/tudatpy#17]
```python
import numpy as np
from tudatpy.kernel import constants
from tudatpy.kernel.interface import spice_interface
from tudatpy.kernel.simulation import environment_setup
from tudatpy.kernel.simulation import propagation_setup
from tudatpy.kernel.astro import conversion

spice_interface.load_standard_kernels()

simulation_start_epoch = 0.0
simulation_end_epoch = constants.JULIAN_DAY

bodies_to_create = ["Sun", "Earth", "Moon", "Mars", "Venus"]

body_settings = environment_setup.get_default_body_settings(
    bodies_to_create,
    simulation_start_epoch,
    simulation_end_epoch,
    "Earth","J2000")

bodies = environment_setup.create_system_of_bodies(body_settings)
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-1e18b48c9338> in <module>
      1 bodies_to_create = ["Sun", "Earth", "Moon", "Mars", "Venus"]
      2 
----> 3 body_settings = environment_setup.get_default_body_settings(
      4     bodies_to_create,
      5     simulation_start_epoch,

TypeError: get_default_body_settings(): incompatible function arguments. The following argument types are supported:
    1. (bodies: List[str], initial_time: float, final_time: float, time_step: float) -> Dict[str, tudatpy.kernel.simulation.environment_setup.BodySettings]
    2. (bodies: List[str]) -> Dict[str, tudatpy.kernel.simulation.environment_setup.BodySettings]

Invoked with: ['Sun', 'Earth', 'Moon', 'Mars', 'Venus'], 0.0, 86400.0, 'Earth', 'J2000'

**Comment by DominicDirkx** [comment]
Indeed, the examples that are in the repository are out of date. We have had to release tudatpy well ahead of schedule due to unforeseen circumstances, and this is one of the points that is still on our long to do list. But, we should have this resolved in the coming weeks.

If you're interested in tudatpy, let us know what you plan to be using it for, it's always great to see people using our project! And, if you're interested there are a whole bunch of aspects of tudat(py) that you could contribute to if you're interested!

**Comment by spacefan** [comment]
The bad experience proves that this is an immature project, maybe I should switch to other tools, such as Orekit, Celestlab, unless I need to use C++ or Python to build application scenarios

**Comment by spacefan** [comment]
The bad experience proves that this is an immature project, maybe I should switch to other tools, such as Orekit, Celestlab, unless I need to use C++ or Python to build application scenarios.
