### ISSUE TITLE
Tudat installation troubles

### ISSUE THREAD

**Issue by Frieskast** [tudat-team/tudatpy#171]
I am having a lot of trouble installing Tudat.

The main problem is that the kernels are not installed or downloaded during the setup.

C:\Users\friso\miniconda3\envs\tudat-space\lib\site-packages\tudatpy\_init_.py", line 2, in <module>
    from .kernel import constants
ImportError: DLL load failed while importing kernel: Cannot find specified procedure.

Where can I manually find these kernels, and in which directory should they be placed?

I appreciate any help you can provide.

**Comment by DominicDirkx** [comment]
Hi, could you specify how you installed tudatpy? Was it through the yaml file on our website? If it was, in the past, the error you get has been caused by virus scanners not allowing Tudat to run.

**Comment by Frieskast** [comment]
Deleting the existing enviroment in minconda3 and than reinstalling using a new yaml seemt to have fixed it. Thank for your help!
