### ISSUE TITLE
Implement a nightly bump version automation workflow

### ISSUE THREAD

**Issue by niketagrawal** [tudat-team/tudatpy#177]
Similar to https://github.com/tudat-team/tudat/issues/232, we need a GitHub action workflow that triggers nightly at a scheduled time and performs the following actions if there is a new commit(s) on the develop branch of tudatpy in the last 24 hours:

1. Bump the version number, create a tag, and push the tag and the bump version commit to the develop branch of the tudatpy repository
2. Bump the version number, create a tag, and push the tag and the bump version commit to the develop branch of the tudatpy repository

Currently, the above actions happen manually. When the develop branch of tudatpy is found to have reached a staged where a new version can be created, the tag and the version is created manually, and the version and tag is added on the tudatpy-feedstock repository, which then triggers the azure pipelines that creates the conda package. 

###NOTE
This workflow must be present in the master branch because scheduled workflows run only on the default branch, so the PR is opened towards master. This version does not make any changes to the master branch of tudat and tudat-feedstock though. This is controlled by specifying the checkout of develop branch in the workflow. This ensures that the bump version action will be performed on the develop branches.

**Comment by niketagrawal** [comment]
This GitHub Actions workflow will require personal access token to bump version, create a tag, and push the tag to tudatpy-feedstock repository. Below are the steps to create a personal access token to use in a Github action:

1. Go to Github profile -> settings > Developer settings (bottom of the menu on the left corner) > Personal access tokens > tokens (classic).
2. Generate new token -> tokens classic. Create a new token by adding a description, for example,  'nightly bump version workflow'

This token must now be specified to use in the tudatpy repository.

1. Got to tudatpy repository -> settings > secrets and variables > actions > new repository secret
2. Name the secret for example, bump_version_nightly. Go to the personal access token created in previous step and copy the token code and paste it as the value of this secret. 
3. Mention this secret name in the bump version github action workflow.

**Comment by yiquintero** [comment]
**Warnings for this workflow**

From the [GitHub documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule), workflows that run on a trigger of type `schedule` (e.g. every night at 3 am) have the following constraints:

> In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. For information on re-enabling a disabled workflow, see "[Disabling and enabling a workflow](https://docs.github.com/en/enterprise-server@3.12/actions/using-workflows/disabling-and-enabling-a-workflow#enabling-a-workflow)."

This warrants no action from our side, but it's good to keep it in mind. Tudat and tudatpy are both very active repos so I don't expect a problem.

> When the last user to commit to the cron schedule of a workflow is removed from the organization, the scheduled workflow will be disabled. If a user with write permissions to the repository makes a commit that changes the cron schedule, the scheduled workflow will be reactivated. Note that, in this situation, the workflow is not reactivated by any change to the workflow file; you must alter the cron value and commit this change.

Since @niketagrawal and myself will leave the project at some point, it would be best for @DominicDirkx to make a change to the [cron trigger in the workflow file](https://github.com/tudat-team/tudat/blob/58ae2e24ec40f327e073d7c5c8af337bab0e1d11/.github/workflows/bump_dev_version_nightly.yml#L21) to prevent the workflow from being disabled.
