### ISSUE TITLE
Solar sail radiation implementation

### ISSUE THREAD

**Issue by tevanham** [tudat-team/tudatpy#20]
The example in the documentation under Solar Sail Radiation Interface gives this error:
`AttributeError: module 'tudatpy.kernel.simulation.environment_setup.radiation_pressure' has no attribute 'solar_sail'`

[documentation](https://tudat-space.readthedocs.io/en/latest/_src_api/environment_setup/create_models/available.html#radiation-pressure-interfaces)

I have searched in this repository for solar sail methods and I did find `RadiationPressureInterfaceSettings` in expose_environment.cpp . I was wondering if this class can be used to generate a Solar Sail Radiation Interface or if there is some other way to do it.

PS: I am using tudatpy for this year's DSE (project group 14) and I was able to set up a model quite quickly, thanks to the clear examples in the documentation.

**Comment by DominicDirkx** [comment]
Quick reply, see below copy-pasted from a similar query last week (in Dutch) concerning the use of this code in the Planetary Sciences II course. The same principle holds for your DSE assignment, I think. Let me know if you'd like to discuss this further

Het solar sailing model in Tudat is niet zo heel goed geschikt voor een 'snel' ontwerp van een baan. Het werkt door functies in te geven die de sail-angles teruggeven. Hoe je die functies op zet is compleet aan de gebruiker (jullie dus). De vrije parameters die deze functies waarschijnlijk zouden hebben, kun je dan optimaliseren.

Als jullie al precies weten hoe je de sail angles wilt parametriseren, kan ik kijken of ik jullie verder kan helpen. Als dit nog niet volledig duidelijk is voor jullie, denk ik helaas dat het ontwerp van een solar sailing baan met Tudat te veel tijd zou kosten voor een PSII assignment,

**Comment by tevanham** [comment]
I have some ideas for the parametrization of the solar sail angles. Namely sinusoid functions or step functions. My tutor (Jeannette Heiligers) specializes in solar sailing, so she could probably also help me with the parametrization.

**Comment by DominicDirkx** [comment]
In that case, send me an e-mail, and we can discuss it further (note that I am our of office on Wednesdays). Still, I doubt that using Tudat for this, which will always do a full propagation of the equations of motion, and will require an optimization loop to get to a transfer that is even valid, is the most effective way to go. But, we can have a discussion over e-mail (or Zoom if needed) to check this.
