### ISSUE TITLE
Feature request: mute std out/std err

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudatpy#29]
A class could be added in the utilities to silence any message that goes through std out and/or std err (both by default).
This can for instance be called using a `with` statement, encapsulating the simulation itself, so that any print message can be directly muted.

**Comment by gaffarelj** [comment]
Implemented this in `tudatpy.util.redirect_std`, pushed in commit [7a14a0b](https://github.com/tudat-team/tudatpy/commit/7a14a0b93bf6eee98f42d2d66fe182f9e2aba51f).

**Comment by DominicDirkx** [comment]
Nice feature, thanks for proposing and adding it! Have you also added an API entry?

**Comment by gaffarelj** [comment]
Yes I have, you can find the associated documentation [here](https://tudatpy.readthedocs.io/en/latest/util.html#tudatpy.util.redirect_std).
