### ISSUE TITLE
Feature request: Pareto optimum solutions

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudatpy#30]
A utility could be added to return an array of booleans representing whether each of the solutions from an optimisation is Pareto-optimal or not.
This can be done for two objectives (to get a Pareto front), or for more than two objectives.

**Comment by gaffarelj** [comment]
This has been implemented as `tudatpy.util.pareto_optimums`, as pushed in commits [733b138](https://github.com/tudat-team/tudatpy/commit/733b138edb3ed234120f86398038966cdecab6da) and [a4f6c56](https://github.com/tudat-team/tudat-multidoc/commit/a4f6c5640a11133066864b94bf9e8b8f28115b86).

The documentation associated with this new function can be seen on [tudatpy API docs](https://tudatpy.readthedocs.io/en/latest/util.html#tudatpy.util.pareto_optimums).

**Comment by DominicDirkx** [comment]
Nice addition, and good initiative. Thanks!
