### ISSUE TITLE
Feature request: 3d plotting

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudatpy#32]
A new function could be added to plot curves in 3D to show the trajectory of a vehicle.

This plot can optionally include different bodies as markers (including a central body), as well as the trajectory from different bodies.

The information for the position (marker) and trajectory (curve) of these body could either be specified by arrays/vectors and strings for the legend, or only as strings and the function will try to access the corresponding dependent variable containing the body position history (and raise an error/warning if this dependent variable does not exist)

**Comment by gaffarelj** [comment]
I was thinking of using `matplotlib.pyplot` for this. From my experience, while it is not directly aimed at this kind of plots, it is the go-to library for plotting in Python.

In my mind, this plotting utility would basically allow to make the [last plot from the thrust_between_Earth_Moon.py example](https://github.com/tudat-team/tudatpy-examples/blob/1f8180b0064226175bbe66e3eaf044f229a897f6/propagation/thrust_between_Earth_Moon.py#L291-L310), except that the user would only need to input body state history (plus fancy options).

**Comment by gaffarelj** [comment]
This tool has been added as `plotting.trajectory_3d()` with 7ec580b5e28772fbb89dac51ffc9dcdec003fba7.

The associated API documentation can be found [here](https://tudatpy.readthedocs.io/en/latest/plotting.html#tudatpy.plotting.trajectory_3d).

**Comment by ggarrett13** [comment]
I won't reopen this, but just fruit for thought, it's common with plotting features in libraries to offer different backends using a `backend` argument (e.g. Poliastro from memory). One could add a `backend=='plotly'` catch to produce interactive plots in Jupyter Notebooks. [Here's an example from my DSE project for an Earth-Jupiter-Pluto trajectory.](https://chart-studio.plotly.com/create/?fid=Jones1311%3A438)

@gaffarelj @DominicDirkx

**Comment by gaffarelj** [comment]
Thanks for the suggestion, but I am not 100% certain of what you mean. Are you suggesting that, depending on what the user inputs for `backend`, I switch the module used for plotting (for instance between `matplotlib` and `plotly`)?

**Comment by geoffreygarrett** [comment]
That's exactly what mean.
