### ISSUE TITLE
tudatpy.kernel.io to be added to the documentation

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudatpy#33]
The `tudatpy.kernel.io` module should be added on [tudatpy.readthedocs.io](https://tudatpy.readthedocs.io). 

It is useful to find where the resources (like space weather) are located on the machine.

**Comment by gaffarelj** [comment]
Actually, not all of it is exposed, only the basics.
Missile datcom  and solar activity data in tudat io could be exposed too.

**Comment by DominicDirkx** [comment]
Indeed, there are various functions/classes in IO that should be documented, and exposed

**Comment by gaffarelj** [comment]
I have created a `feature/document-io` branch in both the `tudatpy` and `tudat-multidoc` repos, to start adding the documentation of the `io` module to the API docs.
For now, I will only include the functions, classes, and enumerations that have already been exposed. (I will not expose anything new for now).

**Comment by gaffarelj** [comment]
To build the API docs for both the C++ methods exposed to Python (such as `get_resource_path`) and direct Python methods (such as `save2txt`) on the same API page, I had to make some changes to the organization of the `io` module.

My changes make all of the io methods available inside the `tudatpy.io` module. Before, the Python methods had to be imported as `tudatpy.io` and the C++ exposed methods as `tudatpy.kernel.io`. With my changes, we thus have `tudatpy.io.save2txt` and `tudatpy.io.get_resource_path` (for instance).

Calling the old `tudatpy.kernel.io` will luckily still work, but will not include the `save2txt` and `save_time_history_to_file` functions. At least, this way, retro-compatibility is assured.

I pushed this changes on a separate branch with 57e73072a2792edea2fda0b52fa245c3006a8329.

**Comment by gaffarelj** [comment]
Also (@FilippoOggionni) I added the `pandas` module as a requirement to the `tudatpy-docs`, `tudat-multidoc`, and the `tudat-bundle` environemnts. This is because the `save2txt` function that is implemented in the `tudatpy.io` module uses `pandas` and the API docs build fail if `pandas` is not installed.

**Comment by DominicDirkx** [comment]
Hi Jeremie, good to see this up! Due to a number of other pressing tasks, I will likely have a look at this by coming Monday or Tuesday at the earliest. Apologies for the delay,

**Comment by gaffarelj** [comment]
Thank you, there is no rush for this indeed 🙂

**Comment by gaffarelj** [comment]
Thanks!

**Comment by FilippoOggionni** [comment]
A bit late in reviewing, but I went through it and have no remarks. Great job!
