### ISSUE TITLE
Feature request: Pareto fronts plotting

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudatpy#43]
A function can be added to the `plotting` module to create `matplotlib` plots comparing two optimization objectives, and to add a Pareto front.

The front is to be placed differently depending on whether the objectives have to be minimized or maximized.

A third objective (or problem value) could be added by the means of a colormap.

**Comment by gaffarelj** [comment]
I have implemented this as the `plotting.pareto_front()` method. Since this feature is quite light and completely separated from anything else, I pushed it directly to develop with 41cc66fe65e3b63cbaae56ba9b22445c835af678.

The documentation is now building and should be shown soon on [this page](https://tudatpy.readthedocs.io/en/latest/plotting.html#tudatpy.plotting.pareto_front).

Please @DominicDirkx  and @FilippoOggionni  tell me if you have any comments about this.

**Comment by DominicDirkx** [comment]
Very nice, with one small request: could you add explicitly in the documentation that this relates to a two-dimensional Pareto front? You can generate Pareto fronts for any number of objectives >1 (but plotting becomes cumbersome as it becomes much 3, 4 or larger...). I would be tempted to modify the function name accordingly as well, but I think we should keep that as it is.

**Comment by gaffarelj** [comment]
I've updated the API docs to make it clearer that this is aimed at dual-objective optimisation. I also renamed the parameter that allows to plot extra information as a colormap, so it doesn't seem like this is a third objective anymore
