### ISSUE TITLE
CMake: "NRLMSISE00::nrlmsise00" target was not found.

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudatpy#48]
Configuring the tudatpy build with the `-DTUDAT_BUILD_WITH_NRLMSISE00=ON`  Cmake option gives a

`Target "kernel" links to target "NRLMSISE00::nrlmsise00" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?`
  
warning in the configuration output, which eventually leads to a 

`ld: library not found for -lNRLMSISE00::nrlmsise00
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)`

Error during the build. 

Issue can be avoided by reducing [this](https://github.com/tudat-team/tudatpy/blob/3b947f4c299971cb5b24101e5b460889f7a06687/CMakeLists.txt#L112) code block in the tudatpy `CMakeLists.txt` to [this](https://github.com/tudat-team/tudatpy/blob/3b947f4c299971cb5b24101e5b460889f7a06687/CMakeLists.txt#L114) single line.

**Comment by briha** [comment]
I had to rollback those changes back to the original block (i.e. reverting the changes done in 0ff7d0f5a0452ac1ccfff54423cf0827870d81c3) for it to compile. Without doing so, it would fail to find the NRLMSISE00 package:

```
CMake Error at tudatpy/CMakeLists.txt:114 (find_package):
  By not providing "FindNRLMSISE00.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "NRLMSISE00", but CMake did not find one.

  Could not find a package configuration file provided by "NRLMSISE00"
  (requested version 0.1) with any of the following names:

    NRLMSISE00Config.cmake
    nrlmsise00-config.cmake

  Add the installation prefix of "NRLMSISE00" to CMAKE_PREFIX_PATH or set
  "NRLMSISE00_DIR" to a directory containing one of the above files.  If
  "NRLMSISE00" provides a separate development package or SDK, be sure it has
  been installed.
```


I was attempting to compile on osx-arm64, which may thus be the issue.
