### ISSUE TITLE
Bug when defining the viability settings

### ISSUE THREAD

**Issue by cfortunylombra** [tudat-team/tudatpy#49]
Hi all,

From the documentation, I found out that there are two ways to put the viability settings into the simulation settings. One way is to put the list with all the viability settings in the following way:
```
observation_simulation_settings.extend(observation.tabulated_simulation_settings_list(
        dict({observation.two_way_doppler_type:observation_settings_list}),observation_times_list,
        viability_settings = viability_settings_list,reference_link_end_type = observation.transmitter))
```
In this way, the number of observations is reduced, in order to comply with the viability requirements set. However, when I add the viability settings into the simulation settings using the following command: 

```
observation.add_viability_check_to_settings(observation_simulation_settings,viability_settings_list) 
``` 
Utilizing the second approach, the number of observations is not reduced during the simulation. This makes me understand that the viability requirements set are not taken into account in the simulation. 

I noticed this when I was developing this [code](https://github.com/cfortunylombra/PRIDE-Doppler-LaRa/blob/main/src/py_preciseorbitdetermination.py). Here, you can find an example of how I define them.

Thank you in advance.

Greetings,
Carlos

**Comment by DominicDirkx** [comment]
Issue has been fixed by an update to tudat: https://github.com/tudat-team/tudat/issues/54
