### ISSUE TITLE
Astroquery Interface (combining pybind11 with native python modules)

### ISSUE THREAD

**Issue by sbcowan** [tudat-team/tudatpy#82]
With the interest in adding an interface with Astroquery, a TudatPy module needs to contain both exposed C++ code (from Tudat) and native python code (from Astroquery). 

Using something similar to [scikit_build_example](https://github.com/pybind/scikit_build_example) makes this possible. When cloned, you can add C++ functions to files in the src/ directory and use pybind to expose them. You can also add native python code to the src/scikit_build_example/ directory. Subsequently, when building with pip (as instructed by the README.md), you can open python, import scikit_build_example, and use pybind and native methods seamlessly.

The issue is that the build methodology used by the scikit repo is different than that of tudatpy, and this needs to be investigated to allow for an Astroquery interface.

**Comment by DominicDirkx** [comment]
Added in #110 and #112
