### ISSUE TITLE
Make it possible to assign default settings of body A to body settings of a body B

### ISSUE THREAD

**Issue by Nosudrum** [tudat-team/tudatpy#89]
Referring to the discussion [here](https://tudat.slack.com/archives/CU777RGUB/p1674151971111349).

The objective being e.g. to create two Earths from default settings, then change the settings of only one. Allowing to create a single Earth from default settings then creating another Earth with a different name and copying the default settings would make it easier.

**Comment by DominicDirkx** [comment]
Code for this has been merge into the develop branches of tudat and tudatpy. You can find the addition to the docs here:

https://github.com/tudat-team/tudat-multidoc/commit/79160ffd32f8e01c7987f0287aaef1a36491f982
