### ISSUE TITLE
Add Native Python Function Layer for Astroquery

### ISSUE THREAD

**Issue by geoffreygarrett** [tudat-team/tudatpy#94]
### Description
This issue is to add a native python function layer for astroquery-sourced ephemeris. A possible method of doing this can be found in [this link](https://github.com/geoffreygarrett/tudatpy/blob/master/tudatpy/_layer_propagation_setup.py)

### Checklist
- [ ] Native python function layer for astroquery
- [ ] Unit Tests
- [ ] Modifications to the changelog

**Comment by DominicDirkx** [comment]
Functionality added in #110 and #112
